name: antidart
description: Anti-Dart.
version: 1.0.0
repository: https://github.com/lehoangbaochung/antidart

environment:
  sdk: ^3.0.5

dependencies:
  test: ^1.21.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
